package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".pb.utils.go"
	gFile := gen.NewGeneratedFile(filename, file.GoImportPath)
	gFile.P("// Code generated by protoc-gen-utils.go. DO NOT EDIT.")
	gFile.P()
	gFile.P("package ", file.GoPackageName)
	gFile.P()
	for _, message := range file.Messages {
		GeneratePool(gFile, message)
		GenFdbMethods(gFile, message)
	}
	return gFile
}
